

remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: air

atom_feed:
  hide: true

repository: JoseLion/ts-routeways

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JoseLion/ts-routeways"

defaults:
  - scope:
      path: ""
    values:
      layout: splash

plugins:
  - jekyll-include-cache