version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:stable

commands:
  bootstrap:
    description: Bootstraps the NodeJS environment along with Yarn and the project dependencies

    steps:
      - checkout:
          path: ~/repos

      - run:
          name: Install NodeJS
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --install' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install yarn
          command: npm install -g yarn

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install packages
          command: yarn install --immutable

      - save_cache:
          paths:
            - ~/repo/ts-routeways/.yarn/cache
          key: yarn-v1-{{ checksum "yarn.lock" }}

jobs:
  build:
    working_directory: ~/repos/ts-routeways
    executor: basic

    steps:
      - bootstrap

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test --forbid-only

workflows:
  main:
    jobs:
      - build
