version: 2.1

executors:
  basic:
    docker:
      - image: cimg/base:stable

commands:
  bootstrap:
    description: Bootstraps the NodeJS environment along with Yarn and the project dependencies
    parameters:
      nodejs:
        description: The NodeJS version to install
        type: string
        default: ""

    steps:
      - checkout:
          path: ~/repos/ts-routeways

      - run:
          name: Install NVM and NodeJS
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --install' >> $BASH_ENV
            source $BASH_ENV

      - when:
          condition: << parameters.nodejs >>
          steps:
            - run:
                name: Install NodeJS v<< parameters.nodejs >>
                command: |
                  nvm install << parameters.nodejs >>
                  nvm use << parameters.nodejs >>
                  nvm alias default << parameters.nodejs >>
                  node --version
      - run:
          name: Install yarn
          command: npm install -g yarn

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install packages
          command: yarn install --immutable

      - save_cache:
          paths:
            - ~/repos/ts-routeways/.yarn/cache
          key: yarn-v1-{{ checksum "yarn.lock" }}

jobs:
  build:
    working_directory: ~/repos/ts-routeways
    executor: basic
    parameters:
      nodejs:
        description: The NodeJS version to install
        type: string

    steps:
      - bootstrap:
          nodejs: << parameters.nodejs >>

      - run:
          name: Compile
          command: yarn compile

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Test
          command: yarn test --forbid-only

  release:
    working_directory: ~/repos/ts-routeways
    executor: basic

    steps:
      - bootstrap

      - run:
          name: Build
          command: yarn build

      - run:
          name: Release
          command: yarn release

workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              nodejs: ["16", "17", "18", "19"]

      - release:
          requires:
            - build
          filters:
            branches:
              only: release
